import Foundation
import SwiftData
import Testing

@testable import Elbert

// The sample decks are written by hand from lecture slides, so the thing worth testing is not the
// content but that the file still parses and still agrees with the engine. A sample deck that
// produced a different card set than the editor would be worse than no sample deck.

@Suite("Sample decks")
@MainActor
struct SampleDataTests {
    private func context() throws -> ModelContext {
        ModelContext(try Persistence.inMemoryContainer())
    }

    @Test("the bundled file parses")
    func parses() throws {
        let decks = try SampleData.bundledDecks(from: Bundle.main)
        #expect(decks.count >= 2)
        #expect(decks.allSatisfy { !$0.notes.isEmpty })
    }

    @Test("every sample note is one the editor would also accept")
    func notesAreValid() throws {
        for deck in try SampleData.bundledDecks(from: Bundle.main) {
            for note in deck.notes {
                var draft = NoteDraft()
                draft.type = note.noteType
                draft.term = note.term
                draft.definition = note.definition
                #expect(draft.canSave, "\(deck.name): \(note.term.prefix(40)) would be rejected")
            }
        }
    }

    @Test("seeding produces decks, notes, and the cards those notes imply")
    func seeding() throws {
        let context = try context()
        let decks = try SampleData.bundledDecks(from: Bundle.main)
        try SampleData.seed(decks, into: context)

        let storedDecks = try context.fetch(FetchDescriptor<Deck>())
        let storedNotes = try context.fetch(FetchDescriptor<Note>())
        let storedCards = try context.fetch(FetchDescriptor<Card>())

        #expect(storedDecks.count == decks.count)
        #expect(storedNotes.count == decks.reduce(0) { $0 + $1.notes.count })

        // Cards are generated by the engine, not described in the JSON, so this is the check that
        // the two agree.
        let expectedCards = storedNotes.reduce(0) { $0 + CardsFromNote.wantedOrdinals(for: $1).count }
        #expect(storedCards.count == expectedCards)
        #expect(storedCards.allSatisfy { $0.state == .new })
    }

    @Test("every seeded note produces at least one card")
    func noOrphanNotes() throws {
        let context = try context()
        try SampleData.seed(try SampleData.bundledDecks(from: Bundle.main), into: context)

        for note in try context.fetch(FetchDescriptor<Note>()) {
            #expect((note.cards?.count ?? 0) >= 1, "\(note.term.prefix(40)) makes no cards")
        }
    }

    @Test("seeding is skipped without the launch argument")
    func requiresLaunchArgument() throws {
        let context = try context()
        #expect(SampleData.seedIfRequested(into: context, arguments: ["Elbert"]) == false)
        #expect(try context.fetch(FetchDescriptor<Deck>()).isEmpty)
    }

    /// The flag means "put the app in a known state", so a second run must leave exactly one copy
    /// of the samples and nothing a previous run added.
    @Test("seeding resets rather than topping up")
    func seedingResets() throws {
        let context = try context()
        let arguments = ["Elbert", SampleData.launchArgument]
        let counter = NewCardCounter(
            defaults: try #require(UserDefaults(suiteName: "sample-tests-\(UUID().uuidString)"))
        )

        #expect(SampleData.seedIfRequested(into: context, arguments: arguments, counter: counter))
        let first = try context.fetch(FetchDescriptor<Deck>()).count

        // Something the person did between launches, which a reset is expected to discard.
        context.insert(Deck(name: "Mine"))
        try context.save()

        #expect(SampleData.seedIfRequested(into: context, arguments: arguments, counter: counter))
        let decks = try context.fetch(FetchDescriptor<Deck>())
        #expect(decks.count == first)
        #expect(!decks.contains { $0.name == "Mine" })
    }

    /// The day counter lives in UserDefaults, not the store, so a reset that forgot it would hand
    /// a fresh set of decks an allowance a previous run had already spent.
    @Test("seeding clears the day counter too")
    func seedingClearsAllowance() throws {
        let context = try context()
        let counter = NewCardCounter(
            defaults: try #require(UserDefaults(suiteName: "sample-tests-\(UUID().uuidString)"))
        )
        let deckID = UUID()
        counter.note(9, deckID: deckID)
        #expect(counter.introduced(deckID: deckID) == 9)

        #expect(SampleData.seedIfRequested(
            into: context,
            arguments: ["Elbert", SampleData.launchArgument],
            counter: counter
        ))
        #expect(counter.introduced(deckID: deckID) == 0)
    }
}
